export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const LOAD_MORE_POSTS_START = 'LOAD_MORE_POSTS_START';
export const LOAD_MORE_POSTS_SUCCESS = 'LOAD_MORE_POSTS_SUCCESS';
export const LOAD_MORE_POSTS_FAILURE = 'LOAD_MORE_POSTS_FAILURE';

export const SEARCH_POSTS = 'SEARCH_POSTS';

export const FETCH_POST_BY_ID_START = 'FETCH_POST_BY_ID_START';
export const FETCH_POST_BY_ID_SUCCESS = 'FETCH_POST_BY_ID_SUCCESS';
export const FETCH_POST_BY_ID_FAILURE = 'FETCH_POST_BY_ID_FAILURE';

export const FETCH_AUTHOR_BY_ID_START = 'FETCH_AUTHOR_BY_ID_START';
export const FETCH_AUTHOR_BY_ID_SUCCESS = 'FETCH_AUTHOR_BY_ID_SUCCESS';
export const FETCH_AUTHOR_BY_ID_FAILURE = 'FETCH_AUTHOR_BY_ID_FAILURE';

export const FETCH_COMMENTS_BY_ID_POST_START = 'FETCH_COMMENTS_BY_ID_POST_START';
export const FETCH_COMMENTS_BY_ID_POST_SUCCESS = 'FETCH_COMMENTS_BY_ID_POST_SUCCESS';
export const FETCH_COMMENTS_BY_ID_POST_FAILURE = 'FETCH_COMMENTS_BY_ID_POST_FAILURE';
